{
 "title": "Panel 2: Calidade Aire",
 "description": "Condicións atmosféricas",
 "tags": [ "panel2" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "options": {
    "content": "<div style=\"text-align: center; color: white; font-size: 30px; font-weight: bold;\">Condicións Atmosféricas</div>\n<div style=\"text-align: center; color: white; font-size: 30px; font-weight: bold;\">Calidade Aire</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n    <img src=\"https://storage.googleapis.com/meteolora_bucket/logo_meteolora.png\" alt=\"Texto alternativo\" width=\"100%\">\n</div>\n"
   }
  },
  {
   "title": "Humidade",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humedad\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Presión atmosférica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presion\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Humidade",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humedad\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Humidade (histórico)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humedad\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Temperatura (histórico)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperatura\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Presión atmosférica",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sea Level Pressure",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presion\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "sea_level_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* .0295301" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Último evento",
   "type": "stat",
   "description": "Último evento recibido",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "micro/esp32/temperatura",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"presion\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Calidade do Aire",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"airq\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Velocidade do Vento",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"velvento\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Velocidade do Vento",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"velvento\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Dirección do vento",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wind",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_rapid_wind",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dirvento\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " * 2.236936" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-socket" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Dirección Vento",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wind Direction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_rapid_wind",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"dirvento\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "wind_direction" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "collector_type", "operator": "=", "value": "remote-socket" },
      { "condition": "AND", "key": "station_name", "operator": "=~", "value": "/^$station_name$/" }
     ]
    }
   ]
  }
 ]
}