{
 "title": "Panel 4: Monitorización Integral da Calidade do Aire",
 "description": "Monitorización Integral da Calidade do Aire",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "options": {
    "content": "<div style=\"text-align: center; color: white; font-size: 30px; font-weight: bold;\">Monitorización Integral </div>\n<div style=\"text-align: center; color: white; font-size: 30px; font-weight: bold;\">Calidade do Aire</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center;\">\n    <img src=\"https://storage.googleapis.com/meteolora_bucket/logo_meteolora.png\" alt=\"Texto alternativo\" width=\"100%\">\n</div>\n"
   }
  },
  {
   "title": "Calidade do Aire",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"airq\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Partículas no aire",
   "type": "bargauge",
   "description": "Partículas de 1, 2,5 e 10 micras",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"part1u\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"part2u5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"part10u\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "description": "Dióxido de carbono: partículas por millón.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"co2ppm\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "description": "CO2 partes por millón",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"co2ppm\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Patículas no aire (histórico)",
   "type": "timeseries",
   "description": "Partículas de 1, 2.5 y 10 micrómetros",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"part1u\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"part2u5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"part10u\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "eCO2",
   "type": "stat",
   "description": "eCO2 partículas por millón",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eco2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "eCO2 (histórico)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eco2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "eCO2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eco2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Compoñentes Orgánicos",
   "type": "stat",
   "description": "Partículas volátiles orgánicas",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "weatherflow_obs",
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tvoc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "relative_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station_name", "operator": "=~", "value": "/^$station_name$/" },
      { "condition": "AND", "key": "collector_type", "operator": "=", "value": "remote-rest" }
     ],
     "tz": "$tz"
    }
   ]
  },
  {
   "title": "Compoñentes Orgánicos histórico",
   "type": "timeseries",
   "description": "Compoñentes Orgánicos histórico",
   "gridPos": { "h": 5, "w": 7, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tvoc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Compoñentes orgánicos",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tvoc\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "NO2, O3, SO2",
   "type": "timeseries",
   "description": "NO2: dióxido de nitróxeno,  O3: ozono, SO2: dióxido de xofre",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"no2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"o3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"so2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "NO2, O3, SO2",
   "type": "bargauge",
   "description": "NO2: dióxido de nitróxeno,  O3: ozono, SO2: dióxido de xofre",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"no2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"o3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"so2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "NO2, O3, SO2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"so2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"o3\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"meteoloradb\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"nodo_feria\")\n  |> filter(fn: (r) => r[\"_field\"] == \"no2\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}